### ISSUE TITLE
Create Demand Gen Twitter Account

### ISSUE THREAD

**Issue by kinlane** [api-specification-toolbox/home#14]
Create an OAI Demand Gen twitter account to just coordinate what is going on in these conversations. share interesting news and goings on, and keep track of who is helping amplify.

**Comment by kinlane** [comment]
I created this account on Twitter [@OAIDemandgen](https://twitter.com/OAIDemandgen). It will be used for the following:

- Tweeting of OAI stories
- Tweeting of ASC stories
- Tweeting of community stories about specification
- Building of Twitter lists for areas of API operations

If you are wanting to get involved, you can follow this account or add to list, and amplify everything published here.

**Comment by tbarn** [comment]
Why not put some of this effort into the https://twitter.com/openapispec account?

**Comment by kinlane** [comment]
This will be a very automated account for distributing information. There is no reason why the @openapispec account can't highlight and showcase everything listed here, but this will be exclusively about organizing the activity across community. 

@OAIDemandGen will just be a broker of stories about tools, and highlighting lists of services and tools in the space. Purely mapping, syndicating, and measuring the reach of demandgen. 

Hopefully it will become more evident once it is setup a little more.
