### ISSUE TITLE
Maintain a registry of specification extensions

### ISSUE THREAD

**Issue by DavidBiesack** [api-specification-toolbox/home#24]
Many API tool providers use [specification extensions](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#specificationExtensions) (`x-` extensions in OpenAPI definitions) specific to their tooling. Mike Ralphson has an [inventory of extensions](https://github.com/Mermade/openapi-specification-extensions).

There does not seem to be a registry of extension that may be useful for API authors so that tools can consume those extensions. 

For example, OpenAPI 2.0 only allows `deprecated` on operations; OpenAPI 3.0 also allow deprecating parameters, schema, etc. A specification annotation in an OpenAPI 2.0 document could mark such features as deprecated, and 2.0 to 3.0 conversion tools could honor a `x-deprecated` extension so that the corresponding feature can be properly tagged as `deprecated` in 3.0 output. Tools like `oas-kit/swagger2openapi` or `api-spec-converted` could honor the `x-deprecated` annotation.

There does not appear to be a place to define such reusable and vendor-neutral extensions.

**Comment by kinlane** [comment]
https://docs.apimatic.io/advanced/swagger-codegen-extensions/
https://cloud.google.com/endpoints/docs/openapi/openapi-extensions
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions.html
https://docs.readme.com/guides/docs/openapi-extensions
https://docs.wso2.com/display/MG301/Supported+OpenAPI+Extensions

**Comment by MikeRalphson** [comment]
Just a note that the list of vendor-documented extensions has been updated recently, it's only the analysis of extensions over GitHub / SwaggerHub / APIs.guru which hasn't been updated since 2017.

The discussion of extensions usable by conversion tools is documented here: https://github.com/Mermade/swaggerplusplus#swaggerplusplus

Specification extensions was originally one of the use-cases for creating the OAS registry site: http://spec.openapis.org/registry/extension/

**Comment by MikeRalphson** [comment]
See also https://github.com/RepreZen/Semoasa#semoasa---specification-extension-metadata-for-oas-annotations-draft for a proposal to make extension definitions themselves machine-readable.

**Comment by DavidBiesack** [comment]
My ASC 2020 presentation discussed specification extensions in general and also demos some of the extension used at Apiture. [YouTube](https://www.youtube.com/watch?v=LrdkJQE4hco) and [slides](https://static.sched.com/hosted_files/asc2020/70/ASC2020%20Open%20APIs%20Wide%20Open.pptx)

**Comment by kinlane** [comment]
I added a direction of extension here - http://api.specificationtoolbox.com/extensions/

The data store behind the listing is here, and can be added to with a pull request - http://api.specificationtoolbox.com/extensions/

**Comment by kinlane** [comment]
I am going to adopt Semoasa - https://github.com/RepreZen/Semoasa to describe each extension.

**Comment by kinlane** [comment]
Now that the toolbox section is up, and I have a label for adding new extensions to the toolbox I am going to close this issue.
