### ISSUE TITLE
Agenda for Friday October 15, 2020

### ISSUE THREAD

**Issue by kinlane** [api-specification-toolbox/home#31]
This is the proposed agenda for Friday October 15, 2020, providing suggestions for discussion during the publicc office hours. Here are the proposed topic to discuss:

- [UK Public Banking API Resource Center](https://postman-toolboxes.github.io/open-banking-uk-public/)
- [Presented the API Specification Toolbox to the OAI BGB](https://docs.google.com/presentation/d/e/2PACX-1vTxA3ClpYnAtSOewc26HRR7CExhXb-5wY_mVFMOhzS_Oyoaa2BMDlZoMw21op1pBw0HYWpE_0hl7uz2/pub?start=false&loop=false&delayms=3000)
- [First Edition of the API Specification Toolbox Newsletter](https://github.com/api-specification-toolbox/newsletter/issues/1)

Add your suggested items below, adding to the agenda discussion. Once done we will link this agenda to the resulting video being published. Keeping the planning for the event out in the open.

**Comment by mniinio** [comment]
- OpenAPI 3.1.0 new RC up for comments and release date in mid-November
- https://oai.github.io/Documentation/ draft site published, any feedback?
- Should we take up 1-2 of the questions for short discussions?
