### ISSUE TITLE
Open Source Tools

### ISSUE THREAD

**Issue by kinlane** [api-specification-toolbox/home#7]
This has been somewhat contentions in the past, however there would be huge value in have a set of open source core libraries that implement functions such as checking correctness of OAI specs. These would be non-commercial and they would not be fully featured "products". Their aim would be to allow people using OAI to do things such as test validity, compliance with the spec etc. Funds would go towards sponsoring development, supporting coordination between developers etc.

**Comment by jglassenberg** [comment]
I'm curious about further supporting internal standardization efforts with linters (https://stoplight.io/open-source/spectral/).  I find as organizations grow that they want to set their own guidelines on how APIs are defined, to have consistency while allowing different teams to have autonomy over their designs.

**Comment by kinlane** [comment]
@jglassenberg I have added a thread to the tooling discussion for this - https://github.com/oai-demandgen/tools/issues/5

**Comment by kinlane** [comment]
This idea is in motion now, and all work will be conducted via the tools GitHub repository - https://github.com/oai-demandgen/tools/

**Comment by kinlane** [comment]
Single Page App - https://postman-toolboxes.github.io/tools/

Data Behind - https://github.com/postman-toolboxes/tools/tree/master/_data

**Comment by kinlane** [comment]
I added a tool section to the API toolbox - http://api.specificationtoolbox.com/tools/

The data store behind is here, and can be added to with a pull request - https://github.com/api-specification-toolbox/toolbox/tree/main/_tools
